# Generated by Django 5.2.13 on 2026-04-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Trailer URL'),
        ),
    ]
