# Generated by Django 5.2.13 on 2026-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='IMDb ID'),
        ),
    ]
