# Generated by Django 5.2.13 on 2026-04-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_movie_tmdb_id_movie_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='rows',
            field=models.PositiveIntegerField(default=10, verbose_name='Count of rows'),
        ),
        migrations.AddField(
            model_name='hall',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=15, verbose_name='Seats per row'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name film'),
        ),
    ]
