# Generated by Django 5.2.13 on 2026-05-01 06:58

from django.db import migrations, models


def copy_movie_genres_to_text(apps, schema_editor):
    Movie = apps.get_model('api', 'Movie')

    # At this migration step Movie still has the M2M field `genres`.
    for movie in Movie.objects.all():
        try:
            names = [g.name for g in movie.genres.all()]
        except Exception:
            names = []

        if names:
            movie.genres_text = ', '.join(names)
            movie.save()


def noop_reverse(apps, schema_editor):
    # We intentionally don't recreate M2M relations on reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cleanup_empty_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(copy_movie_genres_to_text, reverse_code=noop_reverse),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
